LOG[
  ({
    authorities: [[Object]],
    burnt: false,
    compression: {
      asset_hash: 'H77dqWZmPHudBCXYQuujLSzWgAzg4isU8kQUu3ZU1q56',
      compressed: true,
      creator_hash: 'EKDHSGbrGztomDfuiV4iqiZ6LschDJPsFiXjZ83f92Md',
      data_hash: '9TrSYp2zgrZaPMeJKoDtTzY22ssq7DZP7tDxp7BG6dVx',
      eligible: false,
      leaf_id: 19816,
      seq: 19972,
      tree: '4rnLzDBgK3BqDaFGJVzvpYDKGH8mnByMxxrf4HzjhYLq',
    },
    content: {
      $schema: 'https://schema.metaplex.com/nft1.0.json',
      files: [Array],
      json_uri: 'https://arweave.net/GEtNYWLdJSJwRSh5CGraTmNVigJrUILHlzlh5tmdyXk',
      links: [Object],
      metadata: [Object],
    },
    creators: [],
    grouping: [],
    id: '8z1Tx4S42TPrx12vgXXQxQARcxeK5pWeuTGBF8LYuLkq',
    interface: 'V1_NFT',
    mutable: false,
    ownership: {
      delegate: null,
      delegated: false,
      frozen: false,
      owner: '51HLFKrs5tvDwN67PHE1UUM7zLtKzHDu3yqS27U4gMA1',
      ownership_model: 'single',
    },
    royalty: {
      basis_points: 5000,
      locked: false,
      percent: 0.5,
      primary_sale_happened: false,
      royalty_model: 'creators',
      target: null,
    },
    supply: { edition_nonce: 253, print_current_supply: 0, print_max_supply: 0 },
  },
  {
    authorities: [[Object]],
    burnt: false,
    compression: {
      asset_hash: 'APsR42GxCSQYcQkLnQjVj6f33c7iKwBMiGik3UJukc8F',
      compressed: true,
      creator_hash: 'EKDHSGbrGztomDfuiV4iqiZ6LschDJPsFiXjZ83f92Md',
      data_hash: 'D4EC9AuFqZhbjmiMsasvXgweiXKHnFX2EW81pYYatdf',
      eligible: false,
      leaf_id: 19817,
      seq: 19973,
      tree: '4rnLzDBgK3BqDaFGJVzvpYDKGH8mnByMxxrf4HzjhYLq',
    },
    content: {
      $schema: 'https://schema.metaplex.com/nft1.0.json',
      files: [Array],
      json_uri: 'https://arweave.net/D7cd3uuaARCSdR_2zE262Fjw9Xx5WQgebNYD81EeWx0',
      links: [Object],
      metadata: [Object],
    },
    creators: [],
    grouping: [],
    id: '4P7nGmTbdrubs59z4JU8g4YHQPfSyzdMQxxq8i6XYccs',
    interface: 'V1_NFT',
    mutable: false,
    ownership: {
      delegate: null,
      delegated: false,
      frozen: false,
      owner: '51HLFKrs5tvDwN67PHE1UUM7zLtKzHDu3yqS27U4gMA1',
      ownership_model: 'single',
    },
    royalty: {
      basis_points: 5000,
      locked: false,
      percent: 0.5,
      primary_sale_happened: false,
      royalty_model: 'creators',
      target: null,
    },
    supply: { edition_nonce: 253, print_current_supply: 0, print_max_supply: 0 },
  })
]
